import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { LifeBuoy, Mail, MessageSquare, HelpCircle } from "lucide-react";

export default function SupportPage() {
  const faqs = [
    {
      question: "How do the AI tools work?",
      answer: "Our AI tools use advanced large language models (LLMs) to understand your input and generate creative, relevant content. Just provide a topic or keyword, and our AI will handle the rest, providing you with multiple options to choose from."
    },
    {
      question: "Are the generated hashtags up-to-date?",
      answer: "Yes, our AI is trained on vast amounts of data and can identify currently trending and relevant hashtags for your niche, helping you maximize reach and engagement on platforms like Instagram and Facebook."
    },
    {
      question: "Is there a limit to how many times I can use a tool?",
      answer: "Currently, our tools are free to use with generous limits. We are exploring premium plans for heavy users and teams that will offer higher limits and additional features in the future."
    },
    {
      question: "Can I use the generated content for commercial purposes?",
      answer: "Absolutely! All content generated by our tools, such as captions, bios, and descriptions, is yours to use for personal or commercial projects without any attribution required."
    },
    {
      question: "What if I'm not satisfied with the results?",
      answer: "Our tools offer a 'Regenerate' option. If you're not happy with the initial output, simply click it to get a fresh set of ideas. You can also try rephrasing your input topic or keywords for different results."
    }
  ];

  return (
    <div className="bg-background text-foreground">
      <div className="container mx-auto px-4 py-16 sm:px-6 lg:px-8">
        <div className="text-center">
          <h1 className="font-headline text-4xl font-extrabold tracking-tight sm:text-5xl md:text-6xl">
            Support Center
          </h1>
          <p className="mt-6 max-w-2xl mx-auto text-lg text-muted-foreground sm:text-xl">
            We're here to help. Find answers to common questions or get in touch with our team.
          </p>
        </div>

        {/* Contact Options */}
        <div className="mt-16 grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
          <Card className="text-center">
            <CardHeader>
              <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
                <HelpCircle className="h-6 w-6 text-primary" />
              </div>
              <CardTitle className="mt-4 font-headline">FAQs</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                Find quick answers to common questions about our tools and services.
              </p>
            </CardContent>
          </Card>
           <Card className="text-center">
            <CardHeader>
              <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
                <Mail className="h-6 w-6 text-primary" />
              </div>
              <CardTitle className="mt-4 font-headline">Email Us</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                Send us an email at <a href="mailto:support@toolbox.com" className="text-primary hover:underline">support@toolbox.com</a> for detailed inquiries.
              </p>
            </CardContent>
          </Card>
           <Card className="text-center">
            <CardHeader>
              <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
                <MessageSquare className="h-6 w-6 text-primary" />
              </div>
              <CardTitle className="mt-4 font-headline">Live Chat</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                Chat with our support team for real-time assistance (Coming Soon).
              </p>
            </CardContent>
          </Card>
        </div>

        {/* FAQ Section */}
        <div className="mt-20 max-w-3xl mx-auto">
          <h2 className="font-headline text-3xl font-bold text-center mb-8">
            Frequently Asked Questions
          </h2>
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem value={`item-${index}`} key={index}>
                <AccordionTrigger className="text-left font-semibold hover:no-underline">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </div>
  )
}
