
export default function TermsAndConditionsPage() {
  return (
    <div className="bg-background text-foreground">
      <div className="container mx-auto px-4 py-16 sm:px-6 lg:px-8">
        <div className="prose prose-sm sm:prose-base lg:prose-lg dark:prose-invert max-w-none">
          <h1>Terms and Conditions</h1>
          <p className="text-muted-foreground">Last Updated: Aug, 23, 2025</p>

          <h2>1. Agreement to Terms</h2>
          <p>By using our website and tools (the "Service"), you agree to be bound by these Terms and Conditions. If you disagree with any part of the terms, then you do not have permission to access the Service.</p>
          
          <h2>2. Use of Our Services</h2>
          <p>You agree to use our tools for their intended purposes. You are responsible for the content you generate and must ensure it complies with all applicable laws and regulations. You agree not to use the Service to:</p>
          <ul>
            <li>Generate content that is unlawful, harmful, defamatory, obscene, or hateful.</li>
            <li>Infringe upon the intellectual property rights of others.</li>
            <li>Distribute spam or malicious code.</li>
          </ul>

          <h2>3. Generated Content</h2>
          <p>You retain ownership of the text and media you input into our tools. You also own the rights to the content generated for you by the Service. You are solely responsible for verifying the accuracy, and suitability of the generated content for your use case. We do not make any claims about the factual correctness or originality of the AI-generated content.</p>

          <h2>4. Intellectual Property</h2>
          <p>The Service and its original content (excluding content generated by users), features, and functionality are and will remain the exclusive property of Codexign LLC. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Codexign LLC.</p>
          
          <h2>5. Disclaimer of Warranties</h2>
          <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, express or implied, regarding the operation of our Service or the information, content, or materials included therein. You expressly agree that your use of the Service is at your sole risk.</p>

          <h2>6. Limitation of Liability</h2>
          <p>In no event shall Codexign LLC, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>

          <h2>7. Changes to Terms</h2>
          <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms and Conditions on this page.</p>

          <h2>8. Governing Law</h2>
          <p>These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which Codexign LLC is located, without regard to its conflict of law provisions.</p>
          
          <h2>9. Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us at: codexignllc@gmail.com</p>
        </div>
      </div>
    </div>
  );
}
